### ISSUE TITLE
ModuleNotFoundError: No module named 'unidecode'

### ISSUE THREAD

**Issue by lpkeates** [kablekompany/Kable-Kogs#30]
Hello, I seem to have an issue, when trying to load the cog "decancer". This is my traceback:
`Traceback (most recent call last):
  File "c:\users\lpkea\appdata\local\programs\python\python38\lib\site-packages\redbot\core\core_commands.py", line 171, in _load
    await bot.load_extension(spec)
  File "c:\users\lpkea\appdata\local\programs\python\python38\lib\site-packages\redbot\core\bot.py", line 1202, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\lpkea\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\ocean\cogs\CogManager\cogs\decancer\__init__.py", line 2, in <module>
    from .decancer import Decancer
  File "C:\Users\lpkea\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\ocean\cogs\CogManager\cogs\decancer\decancer.py", line 9, in <module>
    import unidecode
ModuleNotFoundError: No module named 'unidecode'`
Is there anything wrong with my code? Also, I love your bot Kable and Pheno <3

**Comment by lpkeates** [comment]
I found the solution, it was to install the module. Silly me!

**Comment by kablekompany** [comment]
Updated requirements was needed in info.json so issue was relevant.
Thanks. stringcase would need to be installed too but that should occur automatically now once you update repo.
